version: "3.8"
services:
  db:
    image: mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
  etherpad:
    image: etherpad/etherpad:latest
    ports:
      - "9001:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
    depends_on:
      - db
  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"
  backend:
    build: .
    image: api
    depends_on:
      - db
      - mail
      - etherpad
    ports:
      - "8080:8080"